from google.cloud import pubsub_v1      # pip install google-cloud-pubsub  ##to install
import glob                             # for searching for json file
import json
import os
import threading
import pymysql                          # pip install pymysql  ##to install

# Search the current directory for the JSON file (including the service account key)
# to set the GOOGLE_APPLICATION_CREDENTIALS environment variable.
files=glob.glob("*.json")
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]=files[0];

# Set the project_id with your project ID
project_id="clarity-staging-4afe8";
subscription_id = "weatherLabels-sub";   # records coming from the producer
output_topic = "weatherStored";          # records going to the consumer

# MySQL server deployed on GKE (external IP of mysql-service)
mysql_ip="34.130.171.25";
db = pymysql.connect(host=mysql_ip, port=3306, user="usr", password="sofe4630u",
                     database="Readings", autocommit=True)

# create the table on the first run. ID is generated by MySQL, so every stored
# record gets a unique key even though the CSV has none.
with db.cursor() as cur:
    cur.execute("""create table if not exists WeatherLabels(
                     ID int auto_increment primary key,
                     time double, profileName varchar(100),
                     temperature double, humidity double, pressure double)""")

# the callback runs on several threads, a single MySQL connection is not thread safe
db_lock = threading.Lock()

subscriber = pubsub_v1.SubscriberClient()
subscription_path = subscriber.subscription_path(project_id, subscription_id)
publisher = pubsub_v1.PublisherClient()
topic_path = publisher.topic_path(project_id, output_topic)

print(f"Storing records from {subscription_path} into MySQL and forwarding them to {topic_path}..\n")

def callback(message: pubsub_v1.subscriber.message.Message) -> None:
    # convert from bytes to dictionary (deserialization)
    record = json.loads(message.data.decode('utf-8'));

    # store the record. None becomes NULL for the missing readings
    with db_lock, db.cursor() as cur:
        cur.execute("insert into WeatherLabels(time, profileName, temperature, humidity, pressure) values(%s,%s,%s,%s,%s)",
                    (record["time"], record["profileName"], record["temperature"], record["humidity"], record["pressure"]))
        record["ID"] = cur.lastrowid;

    # forward the stored record, now carrying its database ID, to the next stage
    publisher.publish(topic_path, json.dumps(record).encode('utf-8')).result()
    print("Stored and forwarded record {}".format(record["ID"]))

    # ack only after the record is safely in MySQL, so nothing is lost if this stage crashes
    message.ack()

with subscriber:
    streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)
    try:
        streaming_pull_future.result()
    except KeyboardInterrupt:
        streaming_pull_future.cancel()
        db.close()
